Repository DSD-DBS/py-capellambse, pull requests merged in 2022-10, with the labels that each got.

#156 Fix launch.json
  .vscode/launch.json
Labels: bug

#157 Add a note for save and update_cache dependance
  capellambse/loader/core.py
  capellambse/loader/filehandler/__init__.py
  capellambse/model/__init__.py
Labels: documentation

#163 Fix class diagrams ([CDB])
  capellambse/aird/capstyle.py
  capellambse/aird/parser/_edge_factories.py
  capellambse/aird/parser/_filters/global.py
  capellambse/svg/drawing.py
  capellambse/svg/symbols.py
Labels: bug, enhancement

#164 Disallow model loading from capella files without valid entrypoint
  capellambse/loader/core.py
  tests/test_model_loading.py
Labels: bug

#165 feat(model): Add reverse attributes to Capabilities and Missions
  capellambse/model/crosslayer/interaction.py
  capellambse/model/layers/ctx.py
  capellambse/model/layers/oa.py
Labels: enhancement

#174 Add `StateTransition.effects`
  capellambse/model/crosslayer/capellacommon.py
  tests/data/melodymodel/5_0/Melody Model Test.aird
  tests/data/melodymodel/5_0/Melody Model Test.capella
  tests/test_model_layers.py
Labels: enhancement
