Repository DSD-DBS/py-capellambse, pull requests merged in 2022-07, with the labels that each got.

#106 #101 Improve documentation of the `GitFileHandler`
  CONTRIBUTING.md
  capellambse/loader/filehandler/__init__.py
  capellambse/loader/filehandler/gitfilehandler.py
Labels: documentation

#109 Minor fixes
  capellambse/extensions/reqif/elements.py
  capellambse/loader/filehandler/gitfilehandler.py
Labels: bug

#111 Fix creating model objects with explicit default values (#108)
  capellambse/loader/xmltools.py
  capellambse/model/common/accessors.py
  tests/test_reqif.py
Labels: bug

#112 ReqIF Attribute Value default __repr__ behaviour
  capellambse/extensions/reqif/elements.py
  tests/test_reqif.py
Labels: enhancement

#118 Add RequirementTypesFolder accessor to RequirementsModule
  capellambse/extensions/reqif/elements.py
Labels: enhancement
